name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  id-token: write

env:
  NODE_VERSION: "24"
  REGISTRY_URL: "https://registry.npmjs.org"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.REGISTRY_URL }}
          cache: 'npm'

      - name: Install & Build
        run: npm ci && npm run build

      - name: Publish to npm
        run: NODE_AUTH_TOKEN="" npm publish
